version: '3'

services:
  postgres-compose:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "12345678"
    ports:
      - "15432:5432"
    volumes:
      - C:\Users\clevisson.cruz\Documentos\Desenvolvimento\Docker-Compose\PostgreSQL
    networks:
      - postgres-compose-network

  app:
    container_name: proposta-spring-boot
    image: proposta:lasted
    build: ./
    ports:
      - "9000:9000"
    environment:
      CARTAO_URL: http://localhost:8888
      ANALISE_URL: http://localhost:9999
      KEYCLOAK_ISSUER_URI: http://localhost:18080/auth/realms/nosso-cartao
      KEYCLOAK_JWKS_URI: http://localhost:18080/auth/realms/nosso-cartao/protocol/openid-connect/certs
      JAEGER_ENDPOINT: http://localhost:14268/api/traces
    depends_on:
      - postgres-compose
    networks:
      - postgres-compose-network

  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "clevissonalgebra@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "PgAdmin2020!"
    ports:
      - "16543:80"
    depends_on:
      - postgres-compose
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge
