
spring:
  application:
    name: proposta
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:15432/postgres}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:12345678}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 9000

feigh:
  client:
    CriaCartao:
      connect-timeout: 100
      read-timeout: 100

management:
  endpoints:
    web:
      exposure:
        include: "info, health"