spring:
  application:
    name: proposta
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:15432/postgres}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:12345678}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:18080/auth/realms/nosso-cartao}
          jwk-set-uri: ${KEYCLOAK_JWKS_URI:http://localhost:18080/auth/realms/nosso-cartao/protocol/openid-connect/certs}

server:
  port: 9000

feigh:
  client:
    CriaCartao:
      connect-timeout: 100
      read-timeout: 100

management:
  endpoints:
    web:
      exposure:
        include: "info,health,prometheus"
    prometheus.enable: true
  metrics:
    tags:
      aplicacao: "Serviço de proposta"
      ambiente: "desenvolvimento"
